/**
 * GENERATED by assets-pipeline/optimise.mjs — do not edit.
 *
 * Metro resolves require() at build time, so bundled art cannot be looked up
 * from a dynamic string. Regenerate after rendering new themes.
 */

/** Pre-rendered Instant Path panels, bundled in the binary (D-10). */
export const STORY_ART: Record<string, number[]> = {
  garden: [
    require('../../assets/stories/garden/01.jpg'),
    require('../../assets/stories/garden/02.jpg'),
    require('../../assets/stories/garden/03.jpg'),
    require('../../assets/stories/garden/04.jpg'),
  ],
  moon: [
    require('../../assets/stories/moon/01.jpg'),
    require('../../assets/stories/moon/02.jpg'),
    require('../../assets/stories/moon/03.jpg'),
    require('../../assets/stories/moon/04.jpg'),
  ],
  train: [
    require('../../assets/stories/train/01.jpg'),
    require('../../assets/stories/train/02.jpg'),
    require('../../assets/stories/train/03.jpg'),
    require('../../assets/stories/train/04.jpg'),
  ],
};

/** Which page each panel takes over on. 4 panels across 12 pages. */
export const PANEL_PAGES: Record<string, number[]> = {
  garden: [1, 4, 8, 11],
  moon: [1, 4, 8, 11],
  train: [1, 4, 8, 11],
};

/**
 * The panel showing on a given page. The player holds each image across
 * several pages via the slow Ken Burns drift (design.md §6) rather than
 * rendering one per page.
 */
export function panelForPage(skeletonId: string, page: number): number | undefined {
  const pages = PANEL_PAGES[skeletonId];
  const art = STORY_ART[skeletonId];
  if (!pages || !art) return undefined;
  let index = 0;
  for (let i = 0; i < pages.length; i++) if (page >= pages[i]!) index = i;
  return art[index];
}
