/**
 * ART-03, second half — optimise rendered art and bundle it into the app.
 *
 *   node assets-pipeline/optimise.mjs
 *
 * **Why bundle rather than serve from Cloud Storage.**
 * design.md §3 gives page 1's illustration a 300ms budget alongside the
 * templated text. A network fetch does not meet that on a bad connection, and
 * the Instant Path image is identical for every user — so shipping it in the
 * binary is both faster and simpler than a CDN round-trip. It also makes the
 * free story work offline from first launch, which matters for a wedge whose
 * child is disproportionately at a grandparent's house or on a plane.
 *
 * Flat vector art compresses extraordinarily well — few gradients, large flat
 * areas — so this is nearly free: ~425KB → ~32KB per panel with no visible
 * loss. 20 themes × 4 panels would still be under 3MB.
 *
 * Custom Path art is per-story and generated at runtime; it is NOT bundled.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';

const SRC = new URL('./out/', import.meta.url).pathname;
const DEST = new URL('../mobile/assets/stories/', import.meta.url).pathname;

/** q:v 4 ≈ quality 90. Verified against the source: no visible artefacts. */
const QUALITY = '4';

mkdirSync(DEST, { recursive: true });

let srcTotal = 0;
let destTotal = 0;
const index = [];

for (const skeleton of readdirSync(SRC, { withFileTypes: true })) {
  if (!skeleton.isDirectory()) continue;
  const id = skeleton.name;
  const inDir = `${SRC}${id}/`;
  const outDir = `${DEST}${id}/`;
  mkdirSync(outDir, { recursive: true });

  const panels = readdirSync(inDir).filter((f) => f.endsWith('.jpg')).sort();
  const emitted = [];

  for (const file of panels) {
    const from = inDir + file;
    const to = outDir + file;
    execFileSync('ffmpeg', ['-v', 'error', '-y', '-i', from, '-q:v', QUALITY, to]);
    srcTotal += statSync(from).size;
    destTotal += statSync(to).size;
    emitted.push(file);
  }

  const manifest = JSON.parse(readFileSync(`${inDir}manifest.json`, 'utf8'));
  index.push({ id, panels: emitted, beats: manifest.beats });
  console.log(`${id.padEnd(8)} ${emitted.length} panels`);
}

/**
 * Which panel is showing on which page. The player holds each image across
 * several pages via the slow Ken Burns drift (design.md §6) rather than
 * rendering one per page — 4 illustrations across 12 pages.
 */
writeFileSync(`${DEST}index.json`, JSON.stringify({ skeletons: index }, null, 2));

/**
 * Emit a TypeScript registry with STATIC require() paths.
 *
 * Metro resolves `require` at build time, so bundled images cannot be looked up
 * from a dynamic string. Generating this file from the same pass that writes
 * the images means the two cannot drift — a hand-maintained list would go stale
 * the first time a theme is added.
 */
const REGISTRY = new URL('../mobile/src/stories/art.ts', import.meta.url).pathname;
mkdirSync(new URL('../mobile/src/stories/', import.meta.url).pathname, { recursive: true });

const body = index
  .map(
    (s) => `  ${s.id}: [
${s.panels.map((p) => `    require('../../assets/stories/${s.id}/${p}'),`).join('\n')}
  ],`,
  )
  .join('\n');

const beats = index
  .map((s) => `  ${s.id}: [${s.beats.map((b) => b.atPage).join(', ')}],`)
  .join('\n');

writeFileSync(
  REGISTRY,
  `/**
 * GENERATED by assets-pipeline/optimise.mjs — do not edit.
 *
 * Metro resolves require() at build time, so bundled art cannot be looked up
 * from a dynamic string. Regenerate after rendering new themes.
 */

/** Pre-rendered Instant Path panels, bundled in the binary (D-10). */
export const STORY_ART: Record<string, number[]> = {
${body}
};

/** Which page each panel takes over on. 4 panels across 12 pages. */
export const PANEL_PAGES: Record<string, number[]> = {
${beats}
};

/**
 * The panel showing on a given page. The player holds each image across
 * several pages via the slow Ken Burns drift (design.md §6) rather than
 * rendering one per page.
 */
export function panelForPage(skeletonId: string, page: number): number | undefined {
  const pages = PANEL_PAGES[skeletonId];
  const art = STORY_ART[skeletonId];
  if (!pages || !art) return undefined;
  let index = 0;
  for (let i = 0; i < pages.length; i++) if (page >= pages[i]!) index = i;
  return art[index];
}
`,
);
console.log(`registry -> mobile/src/stories/art.ts`);

const pct = ((1 - destTotal / srcTotal) * 100).toFixed(1);
console.log(`\n${(srcTotal / 1e6).toFixed(2)}MB → ${(destTotal / 1e6).toFixed(2)}MB  (−${pct}%)`);
console.log(`bundled into mobile/assets/stories/`);
