import type { Metadata } from "next";

import { Bullets, LegalPage, Section } from "@/components/legal";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

export const metadata: Metadata = {
  title: "Terms — Snugglee",
  description:
    "The terms for using Snugglee, including credits, refunds and the rules around voice recording.",
};

/**
 * Required by App Review alongside the privacy policy.
 *
 * Two clauses here are not boilerplate and matter commercially:
 *
 *  - **Credits are consumable and cannot be restored by the store.** Apple only
 *    restores non-consumables and subscriptions. Signing in is the only thing
 *    that carries a balance to a new device, so saying so plainly is both
 *    honest and the reason the app asks.
 *  - **Only your own voice.** We rely on the user's assertion that the voice is
 *    theirs, which is the same posture as every consumer voice product — but it
 *    should be a stated term rather than an unspoken assumption.
 */
export default function Terms() {
  return (
    <>
      <SiteHeader />
      <LegalPage title="Terms of Use" updated="4 August 2026">
        <Section heading="Who can use Snugglee">
          <p>
            You must be 18 or older, and a parent or guardian of the child the
            stories are for. Snugglee is designed to be operated by an adult.
            Children listen; they do not sign up, sign in, or buy anything.
          </p>
        </Section>

        <Section heading="Your voice">
          <p>
            You may only record and use <strong>your own voice</strong>. Do not
            record anyone else — including your partner, a family member, or a
            child — without being that person and having the right to do so.
          </p>
          <p>
            Voices created in Snugglee are for use inside the app, for your own
            family. You may not use the app to impersonate anyone, and we may
            remove a voice and close an account if we believe it has been misused.
          </p>
        </Section>

        <Section heading="Stories and credits">
          <p>
            Your first story is free. After that, stories are made using credits,
            which you buy in packs through the App Store or Google Play.
          </p>
          <Bullets
            items={[
              "One credit makes one new story.",
              "Listening again to a story you already made is always free, as many times as you like.",
              "If a story fails to finish being made, the credit is returned to you automatically.",
              "There is no subscription. Nothing renews on its own and there is nothing to cancel.",
            ]}
          />
          <p>
            Credits have no cash value, cannot be transferred between accounts,
            and cannot be exchanged for money.
          </p>
        </Section>

        <Section heading="Keeping your credits">
          <p>
            Credits are a <strong>consumable</strong> purchase. Apple and Google
            do not restore consumable purchases, which means the store cannot
            give them back to you on a new device.
          </p>
          <p>
            Signing in with Apple links your credits to you rather than to a
            single phone. If you never sign in and you delete the app, change
            phone, or reset your device, your remaining credits cannot be
            recovered. We recommend signing in once you have bought a pack.
          </p>
        </Section>

        <Section heading="Refunds">
          <p>
            Purchases go through the App Store or Google Play, so refunds are
            handled by Apple or Google under their own policies — we cannot issue
            them directly. If something has gone wrong, email{" "}
            <a href="mailto:hello@snugglee.app" className="text-white underline">
              hello@snugglee.app
            </a>{" "}
            and we will help where we can.
          </p>
        </Section>

        <Section heading="About the stories">
          <p>
            Stories are generated by software, using a fixed set of themes we
            have written and checked. Every story passes automated safety checks
            before it is read aloud, and we have deliberately kept the range of
            themes narrow and gentle.
          </p>
          <p>
            Even so, generated content cannot be guaranteed perfect. Stories are
            for entertainment, and a parent should be comfortable with what their
            child is hearing. If you ever see something that troubles you, please
            tell us at{" "}
            <a href="mailto:hello@snugglee.app" className="text-white underline">
              hello@snugglee.app
            </a>{" "}
            — we take it seriously.
          </p>
          <p>
            Stories you create are yours to enjoy privately with your family. We
            do not publish them or share them with anyone.
          </p>
        </Section>

        <Section heading="Acceptable use">
          <p>Please do not:</p>
          <Bullets
            items={[
              "Record a voice that is not your own.",
              "Try to make the app produce content that is unsuitable for a young child.",
              "Attempt to extract, export or resell generated voices or audio.",
              "Interfere with the service or try to access other people's accounts.",
            ]}
          />
        </Section>

        <Section heading="Availability">
          <p>
            We do our best to keep Snugglee working, but we cannot promise it is
            always available. Features may change, and themes may be added or
            retired over time. If we ever stop the service entirely, we will give
            notice and explain what happens to any unused credits.
          </p>
        </Section>

        <Section heading="Liability">
          <p>
            Snugglee is provided as-is. To the extent the law allows, we are not
            liable for indirect or consequential loss. Nothing here limits any
            right you have that cannot legally be limited — including your
            consumer rights.
          </p>
        </Section>

        <Section heading="Changes to these terms">
          <p>
            If we make a material change, we will tell you in the app before it
            takes effect. Continuing to use Snugglee after that means you accept
            the updated terms.
          </p>
        </Section>

        <Section heading="Contact">
          <p>
            <a href="mailto:hello@snugglee.app" className="text-white underline">
              hello@snugglee.app
            </a>
          </p>
        </Section>
      </LegalPage>
      <SiteFooter />
    </>
  );
}
